Simple example to illustrate when VerifyError is happening.